routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $wikis = \App\Models\Wiki::latest()->limit(4)->get();
    return view('welcome', compact('wikis'));
})->middleware('guest');

// Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::view('/about', 'pages.about');
Route::view('/invest', 'pages.invest');
Route::view('/terms', 'pages.terms');
Route::view('/contact', 'pages.contact');



Route::get('/wiki', 'WikisController@index')->name('wikis');
Route::get('/wiki/category:{categoryId}', 'WikisController@index')->name('wikis.show');
Route::get('/wiki/{slug}', 'WikisController@show')->name('wikis.show');

Route::post('/wiki/update/{wiki}', 'WikisController@update')->name('wikis.update');

Route::get('/wiki/{wiki}/body', 'WikisController@getBody')->name('wikis.getBody');
Route::post('/wiki/{wiki}/body', 'WikisController@updateBody')->name('wikis.updateBody');


Route::get('/wiki-section', 'WikiSectionController@index')->name('wikis');
Route::get('/wiki-section/wikiSection:{wikiId}', 'WikiSectionController@index')->name('wikisection.show');
Route::get('/wiki-section/{wikiId}/{sectionId}', 'WikiSectionController@show')->name('wikisection.show');

Route::get('/wiki_section/{wikiSection}/body', 'WikiSectionController@getBody')->name('wikisection.getBody');

Route::post('/image/upload', 'ImageController@upload');


Route::get('/wiki/{wiki}/read', 'ReadWikiController@store');
Route::get('/wiki/{wiki}/unread', 'ReadWikiController@destroy');
// Route::get('/wiki/{wiki}/problem', 'ReadWikiController@show');

Route::post('/wiki/{wiki}/rate', 'RateWikiController@store');

Route::get('/problems/{problem}', 'ProblemsController@get');
Route::get('/problem-question/{question}/question', 'ProblemQuestionsController@getQuestion');
Route::get('/problem-question/{question}/solutions', 'ProblemQuestionsController@getSolutions');
Route::post('/problem-question/{question}/answer', 'ProblemQuestionsController@answer');

Route::delete('/problem-question/solution/{solution}', 'ProblemQuestionSolutionsController@destroy');
Route::put('/problem-question/solution/{solution}', 'ProblemQuestionSolutionsController@update');
Route::post('/problem-question/solution/{solution}/upvote', 'ProblemQuestionSolutionsController@upvote');
Route::post('/problem-question/solution/{solution}/downvote', 'ProblemQuestionSolutionsController@downvote');
Route::post('/problem-question/{question}/solutions', 'ProblemQuestionSolutionsController@store');


Route::get('/discussions', 'DiscussionsController@index');
Route::get('/discussions/filter:{filter}', 'DiscussionsController@index');
Route::post('/discussions', 'DiscussionsController@store');
Route::get('/discussions/{discussion}', 'DiscussionsController@show');
Route::put('/discussions/{discussion}', 'DiscussionsController@update');
Route::get('/discussions/{discussion}/delete', 'DiscussionsController@destroy');

Route::post('/discussions/{discussion}/replies', 'ThreadRepliesController@store');


Route::post('/discussions/replies/{reply}', 'ThreadRepliesController@update');
Route::delete('/discussions/replies/{reply}', 'ThreadRepliesController@destroy');
Route::post('/discussions/replies/{reply}/like', 'ThreadRepliesController@like');
Route::post('/discussions/replies/{reply}/dislike', 'ThreadRepliesController@dislike');

Route::post('/discussions/replies/{reply}/best', 'ThreadRepliesController@best');


Route::get('/practice', 'PracticeController@index');
Route::get('/practice/{subject}/', 'PracticeController@subject');
Route::get('/practice/{subject}/topic:{topic}', 'PracticeController@topic');
Route::get('/practice/{subject}/topic:{topic}/problem:{problem}', 'PracticeController@problem');

Route::get('/books', 'BooksController@index');
Route::get('/books/{subject}', 'BooksController@subject');
Route::get('/books/{subject}/{slug}', 'BooksController@show');
Route::get('/books/{subject}/{slug}/chapter:{chapter}', 'BooksController@chapter');
Route::get('/book-chapter-question/{question}/question', 'BookChapterQuestionsController@getQuestion');
Route::post('/book-chapter-question/{question}/answer', 'BookChapterQuestionsController@answer');

Route::get('/book-chapter-question/{question}/solutions', 'BookChapterQuestionsController@getSolutions');
Route::delete('/book-chapter-question/solution/{solution}', 'BookChapterQuestionSolutionController@destroy');
Route::put('/book-chapter-question/solution/{solution}', 'BookChapterQuestionSolutionController@update');
Route::post('/book-chapter-question/solution/{solution}/upvote', 'BookChapterQuestionSolutionController@upvote');
Route::post('/book-chapter-question/solution/{solution}/downvote', 'BookChapterQuestionSolutionController@downvote');
Route::post('/book-chapter-question/{question}/solutions', 'BookChapterQuestionSolutionController@store');



Route::get('/courses', 'CoursesController@index');
Route::get('/courses/subject:{subjectSlug}', 'CoursesController@index');

Route::get('/courses/{courseSlug}', 'CoursesController@show');
Route::get('/courses/{courseSlug}/chapter:{chapterSlug}', 'CourseChaptersController@show');
Route::get('/courses/{courseSlug}/chapter:{chapterSlug}/section:{sectionSlug}', 'CourseChaptersController@show');

Route::get('/subsections/{subsection}/body', 'SubsectionsController@getArticleBody')->name('subsections.getBody');
Route::get('/course-sections/{section}/body', 'CourseChaptersController@getArticleBody')->name('subsections.getBody');



Route::get('/profile', 'ProfileController@index');
Route::post('/profile', 'ProfileController@updateProfile');
Route::get('/profile/acheivements', 'ProfileController@acheivements');
Route::get('/profile/security', 'ProfileController@security');
Route::post('/profile/security', 'ProfileController@updatePassword');
Route::post('/profile/upload/image', 'ProfileController@fileUpload')->name('profile.upload.image');

Route::get('/profile/upgrade', 'ProfileController@upgrade');
Route::get('/profile/downgrade', 'ProfileController@downgrade');

Route::get('/payment/success', 'ProfileController@upgradeSuccess');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;

class Book extends Model
{
    use CrudTrait;

    protected $table = 'books';
    protected $fillable = ['title', 'description', 'subject_id', 'topic_id', 'image', 'author', 'is_premium'];

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }

    public function chapters()
    {
        return $this->hasMany(BookChapter::class);
    }

    public function questions()
    {
        return $this->hasMany(BookChapterQuestion::class);
    }

    public function topic()
    {
        return $this->belongsTo(Topic::class);
    }

    public function setImageAttribute($value)
    {
        $attribute_name = "image";
        $disk = "public";
        $destination_path = "uploads/books/posters";

        $this->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
    }

     public function getIsOngoingAttribute()
    {
        foreach ($this->questions()->pluck('id') as $key => $id) {
            if(auth()->user()->solvedBookQuestions->contains($id)){
              return true;
            }
        }
        return false;
    }

    public function getIsCompleteAttribute()
    {
        foreach ($this->questions()->pluck('id') as $key => $id) {
          if(!auth()->user()->solvedBookQuestions->contains($id)){
            return false;
          }
        }
        return true;
    }

    public function getIsBlockedAttribute()
    {
        return $this->is_premium && !auth()->user()->is_premium;
    }

    public function manageChapters()
    {
        return '<a class="btn btn-xs btn-primary"   href="/admin/book-chapters?book=' . $this->id . '" data-toggle="tooltip" title="Manage Chapters">Manage Chapters</a>';
    }

    /*
    }
    |--------------------------------------------------------------------------
    | Methods for storing uploaded files (used in CRUD).
    |--------------------------------------------------------------------------
    */

    /**
     * Handle file upload and DB storage for a file:
     * - on CREATE
     *     - stores the file at the destination path
     *     - generates a name
     *     - stores the full path in the DB;
     * - on UPDATE
     *     - if the value is null, deletes the file and sets null in the DB
     *     - if the value is different, stores the different file and updates DB value.
     *
     * @param  [type] $value            Value for that column sent from the input.
     * @param  [type] $attribute_name   Model attribute name (and column in the db).
     * @param  [type] $disk             Filesystem disk used to store files.
     * @param  [type] $destination_path Path in disk where to store the files.
     */
    public function uploadFileToDisk($value, $attribute_name, $disk, $destination_path)
    {
        $request = \Request::instance();

        // if a new file is uploaded, delete the file from the disk
        if ($request->hasFile($attribute_name) &&
            $this->{$attribute_name} &&
            $this->{$attribute_name} != null) {
            \Storage::disk($disk)->delete($this->{$attribute_name});
            $this->attributes[$attribute_name] = null;
        }

        // if the file input is empty, delete the file from the disk
        if (is_null($value) && $this->{$attribute_name} != null) {
            \Storage::disk($disk)->delete($this->{$attribute_name});
            $this->attributes[$attribute_name] = null;
        }

        // if a new file is uploaded, store it on disk and its filename in the database
        if ($request->hasFile($attribute_name) && $request->file($attribute_name)->isValid()) {
            // 1. Generate a new file name
            $file = $request->file($attribute_name);
            $new_file_name = md5($file->getClientOriginalName().time()).'.'.$file->getClientOriginalExtension();

            // 2. Move the new file to the correct path
            $file_path = $file->storeAs($destination_path, $new_file_name, $disk);

            // 3. Save the complete path to the database
            $this->attributes[$attribute_name] = 'storage/' . $file_path;
        }
    }

}

app/Models/Wiki.php
<?php

namespace App\Models;

use App\User;
use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Wiki extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'wikis';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = ['title', 'body', 'wiki_category_id', 'published'];
    // protected $hidden = [];
    // protected $dates = [];


    public function category()
    {
        return $this->belongsTo(WikiCategory::class, 'wiki_category_id');
    }
    public function readers()
    {
        return $this->belongsToMany(User::class, 'wiki_read')->withTimeStamps();
    }

    public function ratings()
    {
        return $this->belongsToMany(User::class, 'wiki_rating')->withTimeStamps()->withPivot('rating');
    }

    public function getRatingAttribute()
    {
        return \DB::table('wiki_rating')->where('wiki_id', $this->id)
                                       ->avg('rating');
    }

    public function getSectionCountAttribute()
    {
        return \DB::table('wiki_sections')->where('wiki_id', $this->id)->count('id');
    }

    public function getReadingsAttribute()
    {
        return $this->readers->count();
    }

    public function getUrlAttribute()
    {
        return 'wiki/' . $this->slug;
    }
    public function manageQuestions()
    {
        return '<a class="btn btn-xs btn-primary"   href="/admin/wiki-problem-questions?wiki=' . $this->id . '" data-toggle="tooltip" title="Manage Problem Questions">Manage Questions</a>';
    }
    public function manageSections()
    {
        return '<a class="btn btn-xs btn-primary"   href="/admin/wikisection?wiki=' . $this->id . '" data-toggle="tooltip" title="Manage Section">Manage Section</a>';
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('content')


<div class="bg-grey-lighter flex fpageresp" style="min-height: 100vh;">
    <div class="container md:mx-auto mt-8 ">
        {{--   <div class="flex flex-col shadow-md rounded bg-white p-4 border-4 border-brand border-l-0 border-b-0 border-r-0">
            <div class="flex border border-grey-dark border-l-0 border-t-0 border-r-0 pb-3">
                <h3 class="flex-1 text-2xl font-semibold tracking-wide mt-1 ml-2">Problems of the week</h3>
                <select class="border-2 border-brand p-2 rounded text-brand font-semibold tracking-wide text-md">
                    <option>1st Week of November</option>
                    <option>1st Week of November</option>
                    <option>1st Week of November</option>
                    <option>1st Week of November</option>
                </select>
            </div>
        <practice-problems problem-set="{{ $problem }}"></practice-problems>
    </div>
    --}}
    <h2 class="text-grey-darkest text-2xl my-4">Latest Wiki Pages</h2>
    <div class="container mx-auto flex mt-8" style="flex-wrap: wrap;">
        @foreach($wikis as $index => $article)
         <a href="{{ url($article->url)}}" class="no-underline text-black w-1/2 pr-6 mb-8">
                                        <div class="rounded shadow-md bg-white p-6 pt-4 border-t-4 border-b-0 border-r-0 border-l-0 border-brand  course-card">

                                            <div class="flex items-center justify-between">
                                                <span class="rounded p-1 px-4 text-white tracking-wide text-xs" style="background-color: {{ $article->category->color->code }}">{{ $article->category->name }}</span>

                                                <rate-wiki id="{{$article->id}}" :edit="false" user-rating="{{$article->rating}}" size="20"></rate-wiki>

                                            </div>

                                            <h3 class="w-full text-xl font-normal tracking-normal leading-normal mt-4 mb-4">
                                                <i class="fa fa-check-circle text-green" v-show="{{ auth()->user()->hasRead($article) }}"></i>  {{ str_limit($article->title, 30) }}
                                            </h3>
                                            <div class="flex justify-between">

                                           {{--  <div class="flex mt-1">
                                                <img class="mr-2" src="/img/studentsicon.png" style="width: 25px;height:100%;">
                                                <span class="text-blue mt-1"> {{$article->readings}} people read this.</span>
                                            </div> --}}

                                         {{--     <span class="text-grey-darker mt-2"><i class="fa fa-clock"></i> {{ $article->created_at->format('jS M Y')}}</span> --}}
                                            </div> 
                                        </div>
                                    </a>
        @endforeach

          <div class="flex justify-center mb-8 mx-w-md" style="margin: auto;">
            <a href="{{ url('/wiki') }}" class="no-underline self-center  bg-transparent hover:bg-brand text-brand-dark font-semibold hover:text-white py-3 px-45 border border-brand hover:border-transparent rounded mr-6">
                  View More
                </a>
        </div>
    </div>


    @if(false)
    <h2 class="text-grey-darkest text-2xl my-4">Recent Practice Problems</h2>
    <div class="container mx-auto mt-8 mb-8" style="flex-wrap: wrap;">
        @foreach($problems as $index => $problem)
         <div href="" class="flex flex-col rounded bg-white shadow-md p-3 pt-4 border-4 border-brand border-l-0 border-b-0 border-r-0 mb-2">

                            <div class="flex items-center justify-between">
                                <div>
                                    <h2 class="text-black font-semibold tracking-wide text-2xl">{{ $problem->title }}</h2>
                                    <p class="text-grey-dark tracking-wide leading-normal mt-3">{{ $problem->description }}</p>
                                </div>


                                    @if($problem->is_complete)
                                        <a href="/practice/{{$problem->subject->slug}}/topic:{{$problem->topic->id}}/problem:{{$problem->slug}}" class="no-underline btn flex bg-orange hover:bg-orande-dark ml-8 mr-4 mt-2 text-white font-semibold uppercase p-3 rounded  tracking-wide text-sm px-8">
                                           <i class="fa fa-check-circle mr-3"></i>  Completed
                                         </a>

                                    @elseif($problem->is_ongoing)
                                            <a href="/practice/{{$problem->subject->slug}}/topic:{{$problem->topic->id}}/problem:{{$problem->slug}}" class="no-underline btn flex bg-blue hover:bg-blue-dark ml-8 mr-4 mt-2 text-white font-semibold uppercase p-3 rounded  tracking-wide text-sm px-8">
                                           <i class="fa fa-play mr-3"></i> Continue
                                          </a>
                                    @else
                                        <a href="/practice/{{$problem->subject->slug}}/topic:{{$problem->topic->id}}/problem:{{$problem->problem->slug}}"  class="no-underline btn flex bg-green hover:bg-green-dark ml-8 mr-4 mt-2 text-white font-semibold uppercase p-3 rounded  tracking-wide text-sm px-8">
                                       <i class="fa fa-play mr-3"></i>  Start
                                     </a>
                                    @endif

                            </div>


                            <div class="flex justify-between mt-4">
                                <div class="flex mt-1">
                                      <img class="mr-2 " src="/img/level.png" style="width: 25px;height:100%;">
                                    <span class="text-blue mt-1 tracking-wide"> {{$problem->level }}</span>

                                    <img class="mr-2 ml-6" src="/img/questions.png" style="width: 25px;height:100%;">
                                    <span class="text-blue mt-1"> {{$problem->questions->count()}} questions</span>


                                </div>

                                 <span class="text-grey-darker mt-2"><i class="fa fa-clock"></i> {{ $problem->created_at->format('jS M Y')}}</span>
                            </div>
                        </div>
        @endforeach
    </div>
    @endif

    @if(count($books) > 0)
    <h2 class="text-grey-darkest text-2xl my-8">Currently Solving Books</h2>
    <div class="container mx-auto mt-8 mb-8" style="flex-wrap: wrap;">
    @foreach($books as $book)
                         <div class="w-1/3 pr-3  rescrd">
                           <div class="flex items-start flex-col shadow-md rounded bg-white mt-8 p-4 border-4 border-brand border-l-0 border-b-0 border-r-0">

                    <h2 class="text-lg">{{ str_limit($book->title, 33) }}</h2>

                    <div class="flex mt-3">
                    <img src="/img/author.png" class="mr-3 booksimg" style="width: 22px;height: 100%;">
                      <p class="mt-1 font-semibold tracking-wide text-sm text-brand">{{ $book->author }}</p>
                     </div>



                    <div class="flex mt-4">
                      <img src="/img/chapters.png" class="mr-3 booksimg mt-1" style="width: 22px;height: 100%;">
                      <p class="mt-2 font-semibold tracking-wide text-brand">{{ $book->chapters->count() }} Chapters</p>

                      <img src="/img/questions.png" class="mr-3 booksimg ml-8 mt-1" style="width: 25px;height: 100%;">
                      <p class="mt-2 font-semibold tracking-wide text-brand">{{ $book->questions->count() }} Questions</p>
                    </div>


                    <div>

                       @if($book->is_complete)
                     <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-6 text-white font-semibold  p-2 rounded  tracking-wide text-sm px-4">
                            <i class="fa fa-check-circle mr-2" style="margin-top: 1px;"></i> Completed
                         </a>
                         @elseif($book->is_ongoing)

                            <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-6 text-white font-semibold  p-2 rounded  tracking-wide text-sm px-4">
                            <i class="fa fa-play mr-2" style="margin-top: 1px;"></i> Continue
                         </a>

                         @else
                           <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-6 text-white font-semibold  p-2 rounded  tracking-wide text-sm px-4">
                           Start Solving <i class="fa fa-arrow-right ml-2" style="margin-top: 1px;"></i>
                         </a>

                         @endif
                         </div>

                  </div>
                  </div>
                         @endforeach
                      </div>
                      @endif

                      @if(count($courses) > 0)
                      <h2 class="text-grey-darkest text-2xl my-4">Ongoing Courses</h2>

                      <div class="flex flex-wrap mt-8 mb-8">
                             @foreach($courses as $course)

                                <a href="/courses/{{$course->slug}}" class="bg-white shadow-md mr-1 rounded p-2 no-underline" style="background: {{$course->color->code}};height: 320px;width: 227px;">
                                    <h4 class="text-xl font-semibold text-white tracking-wide leading-normal pl-2">{{ str_limit($course->title, 20) }}</h4>

                                    <div class="w-100">
                                    <img src="{{ url($course->banner) }}" class="mx-auto block mt-4" style="width: 145px;height: 145px;">
                                    </div>

                                    <p class="text-white tracking-wide leading-normal p-2 text-sm mt-2">{{ str_limit($course->description, 50) }}</p>
                                </a>

                             @endforeach

                         </div>

                        @endif
</div>
</div>
@endsection