routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $wikis = \App\Models\Wiki::latest()->limit(4)->get();
    return view('welcome', compact('wikis'));
})->middleware('guest');

// Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::view('/about', 'pages.about');
Route::view('/invest', 'pages.invest');
Route::view('/terms', 'pages.terms');
Route::view('/contact', 'pages.contact');



Route::get('/wiki', 'WikisController@index')->name('wikis');
Route::get('/wiki/category:{categoryId}', 'WikisController@index')->name('wikis.show');
Route::get('/wiki/{slug}', 'WikisController@show')->name('wikis.show');

Route::post('/wiki/update/{wiki}', 'WikisController@update')->name('wikis.update');

Route::get('/wiki/{wiki}/body', 'WikisController@getBody')->name('wikis.getBody');
Route::post('/wiki/{wiki}/body', 'WikisController@updateBody')->name('wikis.updateBody');


Route::get('/wiki-section', 'WikiSectionController@index')->name('wikis');
Route::get('/wiki-section/wikiSection:{wikiId}', 'WikiSectionController@index')->name('wikisection.show');
Route::get('/wiki-section/{wikiId}/{sectionId}', 'WikiSectionController@show')->name('wikisection.show');

Route::get('/wiki_section/{wikiSection}/body', 'WikiSectionController@getBody')->name('wikisection.getBody');

Route::post('/image/upload', 'ImageController@upload');


Route::get('/wiki/{wiki}/read', 'ReadWikiController@store');
Route::get('/wiki/{wiki}/unread', 'ReadWikiController@destroy');
// Route::get('/wiki/{wiki}/problem', 'ReadWikiController@show');

Route::post('/wiki/{wiki}/rate', 'RateWikiController@store');

Route::get('/problems/{problem}', 'ProblemsController@get');
Route::get('/problem-question/{question}/question', 'ProblemQuestionsController@getQuestion');
Route::get('/problem-question/{question}/solutions', 'ProblemQuestionsController@getSolutions');
Route::post('/problem-question/{question}/answer', 'ProblemQuestionsController@answer');

Route::delete('/problem-question/solution/{solution}', 'ProblemQuestionSolutionsController@destroy');
Route::put('/problem-question/solution/{solution}', 'ProblemQuestionSolutionsController@update');
Route::post('/problem-question/solution/{solution}/upvote', 'ProblemQuestionSolutionsController@upvote');
Route::post('/problem-question/solution/{solution}/downvote', 'ProblemQuestionSolutionsController@downvote');
Route::post('/problem-question/{question}/solutions', 'ProblemQuestionSolutionsController@store');


Route::get('/discussions', 'DiscussionsController@index');
Route::get('/discussions/filter:{filter}', 'DiscussionsController@index');
Route::post('/discussions', 'DiscussionsController@store');
Route::get('/discussions/{discussion}', 'DiscussionsController@show');
Route::put('/discussions/{discussion}', 'DiscussionsController@update');
Route::get('/discussions/{discussion}/delete', 'DiscussionsController@destroy');

Route::post('/discussions/{discussion}/replies', 'ThreadRepliesController@store');


Route::post('/discussions/replies/{reply}', 'ThreadRepliesController@update');
Route::delete('/discussions/replies/{reply}', 'ThreadRepliesController@destroy');
Route::post('/discussions/replies/{reply}/like', 'ThreadRepliesController@like');
Route::post('/discussions/replies/{reply}/dislike', 'ThreadRepliesController@dislike');

Route::post('/discussions/replies/{reply}/best', 'ThreadRepliesController@best');


Route::get('/practice', 'PracticeController@index');
Route::get('/practice/{subject}/', 'PracticeController@subject');
Route::get('/practice/{subject}/topic:{topic}', 'PracticeController@topic');
Route::get('/practice/{subject}/topic:{topic}/problem:{problem}', 'PracticeController@problem');

Route::get('/books', 'BooksController@index');
Route::get('/books/{subject}', 'BooksController@subject');
Route::get('/books/{subject}/{slug}', 'BooksController@show');
Route::get('/books/{subject}/{slug}/chapter:{chapter}', 'BooksController@chapter');
Route::get('/book-chapter-question/{question}/question', 'BookChapterQuestionsController@getQuestion');
Route::post('/book-chapter-question/{question}/answer', 'BookChapterQuestionsController@answer');

Route::get('/book-chapter-question/{question}/solutions', 'BookChapterQuestionsController@getSolutions');
Route::delete('/book-chapter-question/solution/{solution}', 'BookChapterQuestionSolutionController@destroy');
Route::put('/book-chapter-question/solution/{solution}', 'BookChapterQuestionSolutionController@update');
Route::post('/book-chapter-question/solution/{solution}/upvote', 'BookChapterQuestionSolutionController@upvote');
Route::post('/book-chapter-question/solution/{solution}/downvote', 'BookChapterQuestionSolutionController@downvote');
Route::post('/book-chapter-question/{question}/solutions', 'BookChapterQuestionSolutionController@store');



Route::get('/courses', 'CoursesController@index');
Route::get('/courses/subject:{subjectSlug}', 'CoursesController@index');

Route::get('/courses/{courseSlug}', 'CoursesController@show');
Route::get('/courses/{courseSlug}/chapter:{chapterSlug}', 'CourseChaptersController@show');
Route::get('/courses/{courseSlug}/chapter:{chapterSlug}/section:{sectionSlug}', 'CourseChaptersController@show');

Route::get('/subsections/{subsection}/body', 'SubsectionsController@getArticleBody')->name('subsections.getBody');
Route::get('/course-sections/{section}/body', 'CourseChaptersController@getArticleBody')->name('subsections.getBody');



Route::get('/profile', 'ProfileController@index');
Route::post('/profile', 'ProfileController@updateProfile');
Route::get('/profile/acheivements', 'ProfileController@acheivements');
Route::get('/profile/security', 'ProfileController@security');
Route::post('/profile/security', 'ProfileController@updatePassword');
Route::post('/profile/upload/image', 'ProfileController@fileUpload')->name('profile.upload.image');

Route::get('/profile/upgrade', 'ProfileController@upgrade');
Route::get('/profile/downgrade', 'ProfileController@downgrade');

Route::get('/payment/success', 'ProfileController@upgradeSuccess');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;

class Book extends Model
{
    use CrudTrait;

    protected $table = 'books';
    protected $fillable = ['title', 'description', 'subject_id', 'topic_id', 'image', 'author', 'is_premium'];

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }

    public function chapters()
    {
        return $this->hasMany(BookChapter::class);
    }

    public function questions()
    {
        return $this->hasMany(BookChapterQuestion::class);
    }

    public function topic()
    {
        return $this->belongsTo(Topic::class);
    }

    public function setImageAttribute($value)
    {
        $attribute_name = "image";
        $disk = "public";
        $destination_path = "uploads/books/posters";

        $this->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
    }

     public function getIsOngoingAttribute()
    {
        foreach ($this->questions()->pluck('id') as $key => $id) {
            if(auth()->user()->solvedBookQuestions->contains($id)){
              return true;
            }
        }
        return false;
    }

    public function getIsCompleteAttribute()
    {
        foreach ($this->questions()->pluck('id') as $key => $id) {
          if(!auth()->user()->solvedBookQuestions->contains($id)){
            return false;
          }
        }
        return true;
    }

    public function getIsBlockedAttribute()
    {
        return $this->is_premium && !auth()->user()->is_premium;
    }

    public function manageChapters()
    {
        return '<a class="btn btn-xs btn-primary"   href="/admin/book-chapters?book=' . $this->id . '" data-toggle="tooltip" title="Manage Chapters">Manage Chapters</a>';
    }

    /*
    }
    |--------------------------------------------------------------------------
    | Methods for storing uploaded files (used in CRUD).
    |--------------------------------------------------------------------------
    */

    /**
     * Handle file upload and DB storage for a file:
     * - on CREATE
     *     - stores the file at the destination path
     *     - generates a name
     *     - stores the full path in the DB;
     * - on UPDATE
     *     - if the value is null, deletes the file and sets null in the DB
     *     - if the value is different, stores the different file and updates DB value.
     *
     * @param  [type] $value            Value for that column sent from the input.
     * @param  [type] $attribute_name   Model attribute name (and column in the db).
     * @param  [type] $disk             Filesystem disk used to store files.
     * @param  [type] $destination_path Path in disk where to store the files.
     */
    public function uploadFileToDisk($value, $attribute_name, $disk, $destination_path)
    {
        $request = \Request::instance();

        // if a new file is uploaded, delete the file from the disk
        if ($request->hasFile($attribute_name) &&
            $this->{$attribute_name} &&
            $this->{$attribute_name} != null) {
            \Storage::disk($disk)->delete($this->{$attribute_name});
            $this->attributes[$attribute_name] = null;
        }

        // if the file input is empty, delete the file from the disk
        if (is_null($value) && $this->{$attribute_name} != null) {
            \Storage::disk($disk)->delete($this->{$attribute_name});
            $this->attributes[$attribute_name] = null;
        }

        // if a new file is uploaded, store it on disk and its filename in the database
        if ($request->hasFile($attribute_name) && $request->file($attribute_name)->isValid()) {
            // 1. Generate a new file name
            $file = $request->file($attribute_name);
            $new_file_name = md5($file->getClientOriginalName().time()).'.'.$file->getClientOriginalExtension();

            // 2. Move the new file to the correct path
            $file_path = $file->storeAs($destination_path, $new_file_name, $disk);

            // 3. Save the complete path to the database
            $this->attributes[$attribute_name] = 'storage/' . $file_path;
        }
    }

}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Problem;
use App\Models\Subject;
use App\Models\BookChapter;
use Illuminate\Http\Request;

class BooksController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $subjects = Subject::orderBy('name')->get();
        $books = Book::orderBy('title');
        $bookgroup = 'All books';

        if(request()->has('query'))
        {
                $books->where('title', 'LIKE', '%' . request('query') . '%');
                $bookgroup = $bookgroup . ' related to \'' . request('query') . '\'';
        }

        $books = $books->paginate(10);

        return view('books.index', compact('books', 'subjects', 'bookgroup'));
    }

    public function subject($slug)
    {
        $subjects = Subject::orderBy('name')->get();
        $subject = Subject::where('slug', $slug)->first();
        $books = $subject->books()->orderBy('title');
        $bookgroup = 'Books for <b class="font-semibold text-grey-darker">' . $subject->name . "</b>";

        if(request()->has('query'))
        {
                $books->where('title', 'LIKE', '%' . request('query') . '%');
                $bookgroup = $bookgroup . ' related to \'' . request('query') . '\'';
        }
        $books = $books->paginate(10);

        return view('books.index', compact('books', 'subjects', 'subject', 'bookgroup'));
    }

    public function show($subjectSlug, $slug)
    {
        $subject = Subject::where('slug', $subjectSlug)->first();
        $book = Book::where('slug', $slug)->first();
        $problem = Problem::first();
        $startChapter = $book->chapters()->first();
        return view('books.show', compact('subject', 'book', 'startChapter'));
        //return redirect('/books/' . $subject->name . '/' . $book->slug . '/chapter:' . $currentChapter->id);
    }


    public function chapter($subjectSlug, $slug, BookChapter $chapter)
    {
         $subject = Subject::where('slug', $subjectSlug)->first();
         $book = Book::where('slug', $slug)->first();
         $problem = Problem::first();
         $currentChapter = $chapter;
         return view('books.chapter', compact('subject', 'book', 'problem', 'currentChapter'));
    }
}

resources/views/books/_show-sidebar.blade.php
<div  v-if="showSidebar" class="bg-blue-lightest p-4 pr-60" style="min-height: 100vh;">
    <div class="flex flex-col p-4 pl-0 pr-6 mx-3">
      {{--   <button class="shadow bg-transparent hover:bg-green border-2 border-green rounded text-green hover:text-white p-3 px-6 w-full font-semibold tracking-wide">
        <i class="fa fa-star mr-2"></i> Bookmark
        </button> --}}
        <span class="mt-6 text-grey-darker uppercase text-lg font-bold tracking-wide">Chapters</span>
        <ul class="mt-2 list-reset">

            <li class="chapter-item mt-3 text-md">
                  <a href="/books/{{$book->subject->slug}}/{{$book->slug}}" class="no-underline font-semibold tracking-wide hover:text-grey-darker leading-normal {{ !isset($currentChapter) ? 'text-grey-darker' : 'text-grey' }}">
                    <i class="fa fa-book text-xs mr-2"></i> Book Summary
                  </a>
              </li>

            @foreach($book->chapters as $index => $chapter)
                <li class="chapter-item mt-3 text-md">
                  @if($index == 0)
                    <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/chapter:{{$chapter->id}}" class="no-underline font-semibold tracking-wide hover:text-grey-darker leading-normal {{ request()->is('*/chapter:' . $chapter->id) ? 'text-grey-darker' : 'text-grey' }}">
                      <i class="fa fa-circle text-xs mr-2"></i> {{ $chapter->name }}
                    </a>
                  @else
                    @if(auth()->user()->is_premium)
                     <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/chapter:{{$chapter->id}}" class="no-underline font-semibold tracking-wide hover:text-grey-darker leading-normal {{ request()->is('*/chapter:' . $chapter->id) ? 'text-grey-darker' : 'text-grey' }}">
                      <i class="fa fa-circle text-xs mr-2"></i> {{ $chapter->name }}
                    </a>
                    @else
                      <a href="#" class="no-underline font-semibold tracking-wide hover:text-grey-darker leading-normal text-grey">
                      <i class="fa fa-lock text-xs mr-2"></i> {{ $chapter->name }}
                      </a>

                    @endif
                  @endif  
                </li>
            @endforeach

            </ul>
    </div>
</div>

resources/views/books/_sidebar.blade.php
<div class="bg-blue-lightest p-4 pr-60" style="min-height: 100vh;">
    <div class="flex flex-col p-4 pl-0 pr-6 mx-3">
        <span class="mt-6 text-grey-darker uppercase text-lg font-bold tracking-wide">Subjects</span>
        <ul class="mt-2 list-reset">
            <li class="mt-3 text-md">
                    <a href="/books" class="no-underline font-semibold tracking-wide text-grey-darker hover:text-blue-dark {{ request()->is('books')  ? 'text-blue-dark' : '' }} leading-normal">
                         All
                    </a>
                </li>
            @foreach($subjects as $subject)
                <li class="mt-3 text-md">
                    <a href="/books/{{$subject->slug}}" class="no-underline font-semibold tracking-wide text-grey-darker hover:text-blue-dark {{ request()->is('books/' . $subject->slug)  ? 'text-blue-dark' : '' }} leading-normal">
                       {{ $subject->name }}
                    </a>
                </li>
            @endforeach
        </ul>
    </div>
</div>

resources/views/books/chapter.blade.php
@extends('layouts.app')


@section('content')

        <div class="bg-grey-light" >
                 <div class="flex bg-white shadow container md:mx-auto" style="min-height: 100vh;">

          @include('books._show-sidebar')
          <div :class="showSidebar ? 'w-3/4'  : 'w-100'" class="p-6 pl-8">

               <a href="javascript:;" @click.prevent="showSidebar = !showSidebar" class="text-grey-dark no-underline mb-4 font-semibold block"><i class="fa fa-bars"></i> Toggle Sidebar</a>

               <span class="text-blue-dark text-sm font-semibold tracking-wide">
                <a href="/books" class="no-underline text-blue-dark hover:text-brand">
                 Books
                </a>
               {{--  <i class="fa fa-chevron-right text-grey-dark"></i>
                <a href="/books/{{ $subject->slug }}" class="no-underline text-blue-dark hover:text-brand">
                 {{ $subject->name }}
                </a> --}}
                 <i class="fa fa-chevron-right text-grey-dark"></i>
                <a href="/books/{{ $subject->slug }}/{{$book->slug}}" class="no-underline text-blue-dark hover:text-brand">
                {{ $book->title }}
                </a>
                <i class="fa fa-chevron-right text-grey-dark"></i>  <span class="text-grey-darker">
                {{ $currentChapter->name }}</span>
              </span>

                <div class="flex flex-col shadow-md rounded bg-white mt-8 p-4 border-4 border-brand border-l-0 border-b-0 border-r-0">


                <book-chapter problem-set="{{ $currentChapter }}"></book-chapter>
            </div>

          </div>
      </div>
        </div>

@endsection

resources/views/books/index.blade.php
@extends('layouts.app')


@section('content')

        <div class="bg-grey-light" >
                 <div class="flex bg-white shadow container md:mx-auto" style="min-height: 100vh;">

        {{--   @include('books._sidebar') --}}
          <div class="w-full p-6 pl-8">


                <form class=" w-full mx-auto bg-white shadow-md rounded border-2 border-grey mb-6" style="display: flex;margin: 0px!important;">

                      <i class="fa fa-search text-xl ml-3" style="color: #8795a185;margin-top: 10px;"></i>
                      <input type="text" class="w-full  p-2 pt-1 mt-1 text-grey-dark" value="{{ request('query') }}" autocomplete="off" placeholder="Type something..." name="query" style="font-size: 14px;">
                      <button class="btn bg-blue-dark hover:bg-blue-darker text-white font-semibold uppercase p-2 rounded rounded-l-none tracking-wide text-sm px-4">Search</button>

                </form>



                <span class="text-grey-dark text-lg font-semibold tracking-wide">{!! isset($bookgroup) ? $bookgroup : 'All Books'!!}</span>

                <div class="mt-1 mb-4">

                     <div class="flex">
                         @foreach($books as $book)
                         <div class="w-1/2 pr-3">
                           <div class="flex items-start flex-col shadow-md rounded bg-white mt-8 p-4 
                           
                         {{ $book->is_blocked ? 'border-2 border-red pointer-events-none' : 'border-t-4 border-brand'}} ">

                            @if($book->is_blocked)
                               <span class="rounded rounded-full p-2 bg-red text-white absolute" style="left: -10px;top: -10px;"><i class="fa fa-lock"> </i></span>
                             @endif

                     <div class="flex">      
                      <img src="{{ url($book->image) }}" style="width: 160px;height: 160px;">
                     <div class="ml-2">  
                    <h2 class="text-lg">{{ str_limit($book->title, 33) }}</h2>

                    <div class="flex mt-3">
                    <img src="/img/author.png" class="mr-3 booksimg" style="width: 22px;height: 100%;">
                      <p class="mt-1 font-semibold tracking-wide text-sm text-brand">{{ $book->author }}</p>
                     </div>



                    <div class="flex mt-4">
                      <img src="/img/chapters.png" class="mr-3 booksimg mt-1" style="width: 22px;height: 100%;">
                      <p class="mt-2 font-semibold tracking-wide text-brand">{{ $book->chapters->count() }} Chapters</p>

                      <img src="/img/questions.png" class="mr-3 booksimg ml-8 mt-1" style="width: 25px;height: 100%;">
                      <p class="mt-2 font-semibold tracking-wide text-brand">{{ $book->questions->count() }} Questions</p>
                    </div>

                     <div class="bookinline" style="display: inline-block;">

                       @if($book->is_complete)
                     <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-6 text-white font-semibold  p-2 rounded  tracking-wide text-sm px-4">
                            <i class="fa fa-check-circle mr-2" style="margin-top: 1px;"></i> Completed
                         </a>
                         @elseif($book->is_ongoing)

                            <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-6 text-white font-semibold  p-2 rounded  tracking-wide text-sm px-4">
                              <i class="fa fa-play mr-2" style="margin-top: 1px;"></i> Continue
                            </a>

                         @else
                           <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-6 text-white font-semibold  p-2 rounded  tracking-wide text-sm px-4">
                           Start Solving <i class="fa fa-arrow-right ml-2" style="margin-top: 1px;"></i>
                         </a>

                         @endif
                         </div>

                  </div>
                    </div>

                   

                  </div>
                  </div>
                         @endforeach
                     </div>

                </div>

                <div class="mt-6 mb-8">
                    {!! $books->links() !!}
                </div>
          </div>
      </div>
        </div>

@endsection

resources/views/books/show.blade.php
@extends('layouts.app')


@section('content')

        <div class="bg-grey-light" >
                 <div class="flex bg-white shadow container md:mx-auto" style="min-height: 100vh;">

          @include('books._show-sidebar')
          <div :class="showSidebar ? 'w-3/4'  : 'w-100'" class="p-6 pl-8">

            <a href="javascript:;" @click.prevent="showSidebar = !showSidebar" class="text-grey-dark no-underline mb-4 font-semibold block"><i class="fa fa-bars"></i> Toggle Sidebar</a>

               <span class="text-blue-dark text-sm font-semibold tracking-wide">
                <a href="/books" class="no-underline text-blue-dark hover:text-brand">
                 Books
                </a>
              {{--   <i class="fa fa-chevron-right text-grey-dark"></i>
                <a href="/books/{{ $subject->slug }}" class="no-underline text-blue-dark hover:text-brand">
                 {{ $subject->name }}
                </a> --}}
                <i class="fa fa-chevron-right text-grey-dark"></i>  <span class="text-grey-darker">
                {{ $book->title }}</span>
              </span>

                <div class="flex items-start flex-col shadow-md rounded bg-white mt-8 p-4 border-4 border-brand border-l-0 border-b-0 border-r-0"
                 style="padding: 0px 10px!important;">

                    <h2>{{ $book->title }}</h2>

                    <div class="flex mt-3">
                    <img src="/img/author.png" class="mr-3 booksimg " style="width: 22px;height: 100%;">
                      <p class="mt-1 font-semibold tracking-wide text-sm text-brand">{{ $book->author }}</p>
                     </div>

                    <p class="leading-normal tracking-wide text-lg mt-6">
                      {{ $book->description }}
                    </p>

                    <div class="flex mt-6">
                      <img src="/img/chapters.png" class="mr-3 booksimg mt-1" style="width: 22px;height: 100%;">
                      <p class="mt-2 font-semibold tracking-wide text-brand">{{ $book->chapters->count() }} Chapters</p>

                      <img src="/img/questions.png" class="mr-3 booksimg ml-8 mt-1" style="width: 25px;height: 100%;">
                      <p class="mt-2 font-semibold tracking-wide text-brand">{{ $book->questions->count() }} Questions</p>
                    </div>

                    @if(isset($startChapter))
                    <div>
                     @if($book->is_complete)
                     <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/chapter:{{$startChapter->id}}" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-8 text-white font-semibold uppercase p-3 rounded  tracking-wide text-sm px-8">
                           <i class="fa fa-check-circle mr-3"></i>  Completed
                         </a>
                         @elseif($book->is_ongoing)
                             <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/chapter:{{$startChapter->id}}" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-8 text-white font-semibold uppercase p-3 rounded  tracking-wide text-sm px-8">
                           <i class="fa fa-play mr-3"></i>  Continue
                         </a>
                         @else
                           <a href="/books/{{$book->subject->slug}}/{{$book->slug}}/chapter:{{$startChapter->id}}" class="no-underline btn flex bg-orange hover:bg-orande-dark mt-8 text-white font-semibold uppercase p-3 rounded  tracking-wide text-sm px-8">
                            Start Solving <i class="fa fa-arrow-right ml-3"></i>
                         </a>
                         @endif
                         </div>

                  </div>
                  @endif

          </div>
      </div>
        </div>

@endsection