routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $wikis = \App\Models\Wiki::latest()->limit(4)->get();
    return view('welcome', compact('wikis'));
})->middleware('guest');

// Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::view('/about', 'pages.about');
Route::view('/invest', 'pages.invest');
Route::view('/terms', 'pages.terms');
Route::view('/contact', 'pages.contact');



Route::get('/wiki', 'WikisController@index')->name('wikis');
Route::get('/wiki/category:{categoryId}', 'WikisController@index')->name('wikis.show');
Route::get('/wiki/{slug}', 'WikisController@show')->name('wikis.show');

Route::post('/wiki/update/{wiki}', 'WikisController@update')->name('wikis.update');

Route::get('/wiki/{wiki}/body', 'WikisController@getBody')->name('wikis.getBody');
Route::post('/wiki/{wiki}/body', 'WikisController@updateBody')->name('wikis.updateBody');


Route::get('/wiki-section', 'WikiSectionController@index')->name('wikis');
Route::get('/wiki-section/wikiSection:{wikiId}', 'WikiSectionController@index')->name('wikisection.show');
Route::get('/wiki-section/{wikiId}/{sectionId}', 'WikiSectionController@show')->name('wikisection.show');

Route::get('/wiki_section/{wikiSection}/body', 'WikiSectionController@getBody')->name('wikisection.getBody');

Route::post('/image/upload', 'ImageController@upload');


Route::get('/wiki/{wiki}/read', 'ReadWikiController@store');
Route::get('/wiki/{wiki}/unread', 'ReadWikiController@destroy');
// Route::get('/wiki/{wiki}/problem', 'ReadWikiController@show');

Route::post('/wiki/{wiki}/rate', 'RateWikiController@store');

Route::get('/problems/{problem}', 'ProblemsController@get');
Route::get('/problem-question/{question}/question', 'ProblemQuestionsController@getQuestion');
Route::get('/problem-question/{question}/solutions', 'ProblemQuestionsController@getSolutions');
Route::post('/problem-question/{question}/answer', 'ProblemQuestionsController@answer');

Route::delete('/problem-question/solution/{solution}', 'ProblemQuestionSolutionsController@destroy');
Route::put('/problem-question/solution/{solution}', 'ProblemQuestionSolutionsController@update');
Route::post('/problem-question/solution/{solution}/upvote', 'ProblemQuestionSolutionsController@upvote');
Route::post('/problem-question/solution/{solution}/downvote', 'ProblemQuestionSolutionsController@downvote');
Route::post('/problem-question/{question}/solutions', 'ProblemQuestionSolutionsController@store');


Route::get('/discussions', 'DiscussionsController@index');
Route::get('/discussions/filter:{filter}', 'DiscussionsController@index');
Route::post('/discussions', 'DiscussionsController@store');
Route::get('/discussions/{discussion}', 'DiscussionsController@show');
Route::put('/discussions/{discussion}', 'DiscussionsController@update');
Route::get('/discussions/{discussion}/delete', 'DiscussionsController@destroy');

Route::post('/discussions/{discussion}/replies', 'ThreadRepliesController@store');


Route::post('/discussions/replies/{reply}', 'ThreadRepliesController@update');
Route::delete('/discussions/replies/{reply}', 'ThreadRepliesController@destroy');
Route::post('/discussions/replies/{reply}/like', 'ThreadRepliesController@like');
Route::post('/discussions/replies/{reply}/dislike', 'ThreadRepliesController@dislike');

Route::post('/discussions/replies/{reply}/best', 'ThreadRepliesController@best');


Route::get('/practice', 'PracticeController@index');
Route::get('/practice/{subject}/', 'PracticeController@subject');
Route::get('/practice/{subject}/topic:{topic}', 'PracticeController@topic');
Route::get('/practice/{subject}/topic:{topic}/problem:{problem}', 'PracticeController@problem');

Route::get('/books', 'BooksController@index');
Route::get('/books/{subject}', 'BooksController@subject');
Route::get('/books/{subject}/{slug}', 'BooksController@show');
Route::get('/books/{subject}/{slug}/chapter:{chapter}', 'BooksController@chapter');
Route::get('/book-chapter-question/{question}/question', 'BookChapterQuestionsController@getQuestion');
Route::post('/book-chapter-question/{question}/answer', 'BookChapterQuestionsController@answer');

Route::get('/book-chapter-question/{question}/solutions', 'BookChapterQuestionsController@getSolutions');
Route::delete('/book-chapter-question/solution/{solution}', 'BookChapterQuestionSolutionController@destroy');
Route::put('/book-chapter-question/solution/{solution}', 'BookChapterQuestionSolutionController@update');
Route::post('/book-chapter-question/solution/{solution}/upvote', 'BookChapterQuestionSolutionController@upvote');
Route::post('/book-chapter-question/solution/{solution}/downvote', 'BookChapterQuestionSolutionController@downvote');
Route::post('/book-chapter-question/{question}/solutions', 'BookChapterQuestionSolutionController@store');



Route::get('/courses', 'CoursesController@index');
Route::get('/courses/subject:{subjectSlug}', 'CoursesController@index');

Route::get('/courses/{courseSlug}', 'CoursesController@show');
Route::get('/courses/{courseSlug}/chapter:{chapterSlug}', 'CourseChaptersController@show');
Route::get('/courses/{courseSlug}/chapter:{chapterSlug}/section:{sectionSlug}', 'CourseChaptersController@show');

Route::get('/subsections/{subsection}/body', 'SubsectionsController@getArticleBody')->name('subsections.getBody');
Route::get('/course-sections/{section}/body', 'CourseChaptersController@getArticleBody')->name('subsections.getBody');



Route::get('/profile', 'ProfileController@index');
Route::post('/profile', 'ProfileController@updateProfile');
Route::get('/profile/acheivements', 'ProfileController@acheivements');
Route::get('/profile/security', 'ProfileController@security');
Route::post('/profile/security', 'ProfileController@updatePassword');
Route::post('/profile/upload/image', 'ProfileController@fileUpload')->name('profile.upload.image');

Route::get('/profile/upgrade', 'ProfileController@upgrade');
Route::get('/profile/downgrade', 'ProfileController@downgrade');

Route::get('/payment/success', 'ProfileController@upgradeSuccess');

app/Models/Discussion.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Discussion extends Model
{
    protected $fillable = ['title', 'body', 'user_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function replies()
    {
        return $this->hasMany(ThreadReply::class);
    }

    public function markBestReply(ThreadReply $reply)
    {
        $this->best_reply_id = $reply->id;

        $this->save();
    }

    public function getIsClosedAttribute()
    {
        return $this->best_reply_id != 0;
    }

    public function scopeClosed (Builder $query) {
        return $query->where('best_reply_id', '!=' , 0);
    }

    public function scopePopular (Builder $query) {
        return $query->has('replies', '>' , 5);
    }

    public function scopeUnanswered (Builder $query) {
        return $query->has('replies', '==' , 0);
    }

}

app/Http/Controllers/DiscussionsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Discussion;
use Illuminate\Http\Request;

class DiscussionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($filter = null)
    {
        $threadgroup = 'All Threads';

        if(isset($filter))
        {
            if($filter == 'mine')
            {
                $discussions = auth()->user()->discussions()->latest();
                $threadgroup = 'My Threads';
            } else if($filter == 'popular') {
                $discussions = Discussion::latest()->popular();
                $threadgroup = 'Popular Threads';
            } else if($filter == 'unanswered') {
                $discussions = Discussion::latest()->unanswered();
                 $threadgroup = 'Unanswered Threads';
            } else if($filter == 'closed') {
                $discussions = Discussion::latest()->closed();
                 $threadgroup = 'Closed Threads';
            } else {
                return redirect('/discussions');
            }
        } else {
            $discussions = Discussion::latest();
        }

        if(request()->has('query') && request('query') != '')
        {
            $discussions = $discussions->where('title', 'LIKE', '%' . request('query') . '%')->paginate(10);
            $threadgroup =  $threadgroup . ' related to \'' . request('query') . '\'';
        } else {
            $discussions = $discussions->paginate(10);
        }

        return view('discussions.index', compact('discussions', 'threadgroup'));
    }

    public function store()
    {
        request()->validate([
            'title' => 'required',
            'body'  => 'required'
        ]);

        $discussion = auth()->user()->discussions()->create(['title' => request('title'), 'body' => request('body')]);

        return response(['discussion_id' => $discussion->id], 200);
    }

    public function update(Discussion $discussion)
    {
        request()->validate([
            'title' => 'required',
            'body'  => 'required'
        ]);

        $discussion->update(['title' => request('title'), 'body' => request('body')]);

        return response(['discussion_id' => $discussion->id], 200);
    }

    public function show(Discussion $discussion)
    {
        return view('discussions.show', compact('discussion'));
    }

    public function destroy(Discussion $discussion)
    {
        $discussion->delete();

        return redirect('/discussions');
    }
}

resources/views/discussions/_discussion.blade.php
<div class="flex mt-8  pb-8 border-t-0 border-x-0 border-b border-grey-light">
    <img class="rounded-full" src="/img/user.png" style="width: 45px;height: 45px;">
    <div class="flex flex-col ml-4 w-full">
        <a href="{{ url('/discussions/' . $discussion->id) }}" class="no-underline">
            <h4 class="text-xl text-blue-dark font-semibold">
            {{ $discussion->title }}
            </h4>
        </a>
        <span class="text-sm mt-2 text-black font-semibold">
            Posted by :
            <a class="no-underline text-blue" href="#">{{ $discussion->user->name }}</a>
        </span>
        <div class="mt-4 text-lg text-black leading-normal">
        <platex body="{{ $discussion->body }}"></platex>
    </div>
    <div class="mt-6 flex justify-between">
        <div class="flex">
            <span class="bg-grey-light mr-8 rounded text-md font-semibold text-grey-darker p-2">
                @if($discussion->is_closed)
                    <i class="fa fa-circle text-red text-xs mr-2"></i> Closed
                @else
                    <i class="fa fa-circle text-green text-xs mr-2"></i> Open
                @endif
            </span>
           {{--  <span class="text-md font-semibold mr-6 text-grey-dark pt-2">
                <i class="fa fa-eye  mr-1"></i> 0 Visits
            </span> --}}
            <span class="text-md font-semibold mr-6 text-grey-dark pt-2">
                <i class="fa fa-comments  mr-1"></i> {{ $discussion->replies->count() }} Replies
            </span>
        </div>
        <a href="{{ url('/discussions/' . $discussion->id) }}" class="no-underline border  bg-white text-grey-dark -mt-1 pb-1 pt-2 px-3 text-sm font-semibold rounded">
            read more
        </a>
    </div>
</div>
</div>

resources/views/discussions/_newReply.blade.php
<div class="mt-6 ml-8 pl-8 mb-8 pb-8">
    <form action="/discussions/{{$discussion->id}}/replies" method="POST">
        @csrf
        <textarea name="body" class="w-full border h-32 p-2 rounded" required="required">

        </textarea>
         <span  class="text-sm mt-1 tracking-wide text-grey-dark block">You can use <b class="font-semibold">latex</b> and <b class="font-semibold">markdown</b> to add more pretty replies.</span>

         <button type="submit" class="bg-green mt-3 hover:bg-green-dark shadow rounded text-white p-2 px-6 font-semibold text-sm tracking-wide">Post Reply</button>

    </form>
</div>

resources/views/discussions/_show.blade.php
<div class="flex mt-8">
      <img class="rounded-full" src="/img/user.png" style="width: 45px;height: 45px;">
      <div class="flex flex-col ml-4 w-full">
            <a href="#" class="no-underline">
              <h4 class="text-xl text-blue-dark font-semibold">
              {{ $discussion->title }}
              </h4>
            </a>

            <span class="text-sm mt-2 text-black font-semibold">
              Posted by :
              <a class="no-underline text-blue mr-2" href="#">{{ $discussion->user->name }}</a>
              @if(auth()->user()->isCreaterOf($discussion))
              | <a class="no-underline hover:underline text-grey-darker mr-2 ml-1" @click.prevent="showModal('edit-thread')"  href="#">Edit</a>
              | <a class="no-underline hover:underline text-grey-darker ml-1" href="/discussions/{{$discussion->id}}/delete">Delete</a>
              @endif
            </span>

            <div class="mt-4 text-lg text-black leading-normal">
              <platex body="{{ $discussion->body }}"></platex>
            </div>
            <hr class="w-full border-grey-lighter border mt-8">
            @foreach($discussion->replies as $reply)
              <div>
                <thread-reply :owned-thread={{ auth()->user()->isCreaterOf($discussion) ? 'true' : 'false' }} reply-data="{{ json_encode($reply) }}"></thread-reply>
              </div>
            @endforeach
    </div>
</div>

resources/views/discussions/_sidebar.blade.php
<div class="bg-blue-lightest p-4 pr-55" style="min-height: 100vh; ">
    <div class="flex flex-col p-4 pl-0 pr-6 mx-3">
        <button @click="showModal('new-thread')" class="shadow bg-green hover:bg-green-dark rounded text-white p-3 px-6 font-semibold tracking-wide">
        Add New Thread
        </button>
        <span class="mt-6 text-grey-darker uppercase text-sm font-bold tracking-wide">Browse</span>
        <ul class="mt-2 list-reset">
            <li class="mt-2 text-md">
                <a href="/discussions" class="no-underline font-semibold tracking-wide text-grey-darker hover:text-blue-dark {{ request()->is('discussions') ? 'text-blue-dark' : '' }}">
                    <i class="fa fa-comments mr-1"></i> All Threads
                </a>
            </li>
            <li class="mt-4 text-md">
                <a href="/discussions/filter:mine" class="no-underline font-semibold tracking-wide text-grey-darker hover:text-blue-dark {{ request()->is('discussions/filter:mine') ? 'text-blue-dark' : '' }}">
                    <i class="fa fa-user mr-2"></i> My Threads
                </a>
            </li>
            <li class="mt-4 text-md">
                <a href="/discussions/filter:popular" class="no-underline font-semibold tracking-wide text-grey-darker hover:text-blue-dark {{ request()->is('discussions/filter:popular') ? 'text-blue-dark' : '' }}">
                    <i class="fa fa-star mr-1"></i> Popular Threads
                </a>
            </li>
             <li class="mt-4 text-md">
                <a href="/discussions/filter:closed" class="no-underline font-semibold tracking-wide text-grey-darker hover:text-blue-dark {{ request()->is('discussions/filter:closed') ? 'text-blue-dark' : '' }}">
                    <i class="fa fa-thumbs-up mr-1"></i> Closed Threads
                </a>
            </li>
            <li class="mt-4 text-md">
                <a href="/discussions/filter:unanswered" class="no-underline font-semibold tracking-wide text-grey-darker hover:text-blue-dark {{ request()->is('discussions/filter:unanswered') ? 'text-blue-dark' : '' }}">
                    <i class="fas fa-question-circle mr-1"></i> Unanswered Threads
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/discussions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="bg-grey-lightest">
      <div class="flex bg-white shadow container md:mx-auto" style="min-height: 100vh;">

          @include('discussions._sidebar')
          <div class="w-3/4 p-6 pl-8">


                <form class=" w-full mx-auto bg-white shadow-md rounded border-2 border-grey mb-6" style="display: flex;">

                      <i class="fa fa-search text-xl ml-3" style="color: #8795a185;margin-top: 10px;"></i>
                      <input type="text" class="w-full  p-2 pt-1 mt-1 text-grey-dark" value="{{ request('query') }}" autocomplete="off" placeholder="Type something..." name="query" style="font-size: 14px;
                       margin-bottom: 0px!important;">
                      <button class="btn bg-blue-dark hover:bg-blue-darker text-white font-semibold uppercase p-2 rounded rounded-l-none tracking-wide text-sm px-4">Search</button>

                </form>



                <span class="text-grey-dark text-md font-semibold tracking-wide">{{ isset($threadgroup) ? $threadgroup : 'All Threads'}}</span>
                @foreach($discussions as $discussion)
                   @include('discussions._discussion')
                @endforeach

                <div class="mt-6">
                  {!! $discussions->links() !!}
                </div>
          </div>
      </div>
    </div>

     @include('discussions.new-modal')
@endsection

resources/views/discussions/new-modal.blade.php
<new-thread></new-thread>

resources/views/discussions/show.blade.php
@extends('layouts.app')
@section('content')
<div class="bg-grey-lightest">
  <div class="flex bg-white shadow container md:mx-auto" style="min-height: 100vh;">

    @include('discussions._sidebar')

    <div class="w-3/4 p-6 pl-8">
      <span class="text-blue-dark text-sm font-semibold tracking-wide">
        <a href="/discussions" class="no-underline text-blue-dark hover:text-brand">
          {{ isset($threadgroup) ? $threadgroup : 'All Threads' }}
        </a>
        <i class="fa fa-chevron-right text-grey-dark"></i> {{ $discussion->title }}
      </span>

      @include('discussions._show')

      @include('discussions._newReply')

    </div>
  </div>
</div>
@include('discussions.new-modal')

<edit-thread thread="{{ json_encode($discussion) }}"></edit-thread>
@endsection